object Versions {
    const val gradlePlugin = "7.0.1"
    const val hiltGradlePlugin = "2.38.1"
    const val kotlin = "1.6.10"
    const val parseSdk = "1.25.0"
    const val coroutines = "1.5.1"
    const val navigation = "2.4.0-alpha10"
    const val hiltNavigation = "1.0.0-alpha03"
    const val hilt = "2.38.1"
    const val lifecycle = "2.3.1"
    const val timber = "5.0.1"
    const val compose = "1.1.1"
    const val core = "1.6.0"
    const val appCompat = "1.3.1"
    const val activityCompose = "1.3.1"
    const val material = "1.4.0"
    const val coil = "1.3.2"
    const val coilLandscapist = "1.3.6"
}
