# This is a basic workflow to help you get started with Actions

name: Build


# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Detekt
        run: ./gradlew detekt
      - name: Run Unit tests
        run: ./gradlew test
      - name: Collect actifacts
        if: always()
        run: 
            mkdir artifacts
            cp app/build/reports/detekt/detekt.html artifacts/
      - name: Download detekt report
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: artifacts
   

    

